#pragma config(Motor,  port2,           servo1,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (1 == 1){
		if(vexRT[Btn5U] == 1)       	//If button 5U is pressed...
		{
			motor[servo1] = 127;    	//...raise the arm.
		}
		else if(vexRT[Btn5D] == 1)  	//Else, if button 5D is pressed...
		{
			motor[servo1] = -127;   	//...lower the arm.
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[servo1] = 0;      	//...stop the arm.
		}
	}


}
