#pragma config(Motor,  port2,           servo1,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           servo2,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int angle = 0;
bool angleSetCooldown = false; // meant to slow do
const float angleIterationInterval = 1000; // in milliseconds

void angleCooldown(){
	angleSetCooldown = true;
	clearTimer(T1);
	while(time1[T1] < angleIterationInterval){
		continue; //might be useless
	}
	angleSetCooldown = false;
}

void angleIncrease(){
	angle++;
	angleCooldown();
}

void angleDecrease(){
	angle--;
	angleCooldown();
}


task main()
{
	while (1 == 1){
		/*
		if(vexRT[Btn5U] == 1)       	//If button 5U is pressed...
		{
			motor[servo1] = 127;    	//...raise the arm.
		}
		else if(vexRT[Btn5D] == 1)  	//Else, if button 5D is pressed...
		{
			motor[servo1] = -127;   	//...lower the arm.
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[servo1] = 0;      	//...stop the arm.
		}
		*/
		motor[servo2] = angle;
		if(!angleSetCooldown){
			if((vexRT[Btn5D] == 1) && (angle < 127)){
				angleIncrease();
			} else if ((vexRT[Btn6D] ==1) && (angle > -127)){
				angleDecrease();
			}
		}



}
}

